name: run
description: "Run the library"

runs:
  using: "composite"
  steps:
    # Build the project
    - name: run
      shell: bash
      run: |
        if [ "${{ matrix.name }}" == "Windows-x86_64" ]; then
          ./build/main.exe
        else
          ./build/main
        fi