name: build_test

on:
  workflow_call:
  workflow_dispatch: # lets you run a build from github.com
  # Runs the workflow on all push events
  pull_request:
    branches:
      - main

env:
  SCCACHE_GHA_ENABLED: "true"

# When pushing new commits, cancel any workflows with the same name on that branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux-x86_64
            os: ubuntu-latest
          - name: macOS-x86_64
            os: macOS-latest
          - name: macOS-arm64
            os: macOS-latest
          - name: Windows-x86_64
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: get repo and submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: setup
        uses: ./.github/actions/setup
      - name: build
        uses: ./.github/actions/build
        with:
          # Asserts do not work in release builds!
          BUILD_TYPE: Debug
          CMAKE_BUILD_PARALLEL_LEVEL: 4
          CMAKE_BUILD_ARGS: "-DWITH_TESTS=ON"
          TARGETS: (main test)
      - name: test
        uses: ./.github/actions/test
  # Matrix strategy job results cannot be directly used as required status checks
  # Therefore, we need to check the result of the test job in a separate job as workaround
  test_result:
    needs: build_test
    runs-on: ubuntu-latest
    # This is needed otherwise the job will not run if the build_test job fails and the status check will waiting for an answer
    if: always()
    steps:
      - name: check test results
        run: |
          echo "The test was a: ${{ needs.build_test.result }}"
          if [ ${{ needs.build_test.result }} == "failure" ]; then
            echo "The test failed"
            exit 1
          else
            echo "The test passed"
            exit 0
          fi
